version: "3"
services:
  # Back
  back:
    build: ./back/
    restart: on-failure
    expose:
      - "8000"
    volumes:
      - ./back:/app
    networks:
      - web_network
    depends_on:
      - database
    environment:
      FLASK_DEBUG: 1
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: bd_user
      DB_PASSWORD: "@cp3devops"
      DB_NAME: bdcp3
      AUTH_PLUGIN: mysql_native_password
  # Web
  web:
    build: ./web/
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - web_network
  # Banco
  database:
    container_name: bdcp3
    image: mysql:8.2
    restart: on-failure
    environment:
      MYSQL_USER: bd_user
      MYSQL_PASSWORD: "@cp3devops"
      MYSQL_DATABASE: bdcp3
      MYSQL_ROOT_PASSWORD: "@cp3devops"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
     - web_network
    volumes:
      - db_data:/var/lib/mysql
networks:
  web_network:
volumes:
  db_data:
  web: